// Register the block
wp.blocks.registerBlockType('nxt/nxt-dark-mode-switcher', {
	title: 'Dark Mode Switcher',
	icon: 'button',
	category: 'nxt-addons',
	attributes: {
		// You can define attributes here if you need to
	},
	edit: function(props) {
		return wp.element.createElement(
			'p',
			null,
			'nxt Dark Mode Switcher'
		);
	},
	save: function() {
		return null; // This means the content will be generated by PHP
	}
});